"""Add full album fields

Revision ID: 010941cb08c5
Revises: c10d28be10cf
Create Date: 2025-07-03 22:34:22.563120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010941cb08c5'
down_revision = 'c10d28be10cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('credits', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('credits')
        batch_op.drop_column('artist')
        batch_op.drop_column('cover_url')
        batch_op.drop_column('price')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
