"""Fix duplicate fields in Image

Revision ID: 12111889292e
Revises: eb3eb25dc4e4
Create Date: 2025-07-01 21:58:26.452591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12111889292e'
down_revision = 'eb3eb25dc4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
